name = "MultiFloats"
uuid = "bdf0d083-296b-4888-a5b6-7498122e68a5"
authors = ["David K. Zhang <dzhang314@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.0"
